version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_service
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   # Port dla komunikacji AMQP
      - "15672:15672" # Panel webowy (login: guest, pass: guest)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rabbitmq-network

  mongodb:
    image: mongo:7
    container_name: mongodb_service
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"  # Port dla MongoDB
    volumes:
      - mongodb_data:/data/db  # Persistentna pamięć dla danych
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rabbitmq-network

  producer:
    build: ./producer
    container_name: log_producer
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq-network

  # Konsument nr 1: Loguje tylko błędy
  error_logger:
    build: ./consumer
    container_name: error_logger
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - BINDING_KEY=*.error
      - CONSUMER_NAME=ALERCIARZ
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/rabbitmq_logs
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - rabbitmq-network

  # Konsument nr 2: Loguje wszystko (archiwum)
  archive_logger:
    build: ./consumer
    container_name: archive_logger
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - BINDING_KEY=#
      - CONSUMER_NAME=ARCHIWIZATOR
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/rabbitmq_logs
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - rabbitmq-network

volumes:
  mongodb_data:

networks:
  rabbitmq-network:
    driver: bridge